version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/joshbeard/walsh"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"